/**
 *
 * GeoBricks
 *
 * Copyright (c) 2011 by Kalimaha
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.geobricks.gdal.constant;

/**
 * 
 * @author <a href="mailto:guido.barbaglia@gmail.com">Guido Barbaglia</a>
 * 
 */
public enum CONFIG {

	CPL_DEBUG, CPL_LOG, CPL_LOG_ERRORS, CPL_TIMESTAMP, CPL_MAX_ERROR_REPORTS, 
	CPL_ACCUM_ERROR_MSG, CPL_TMPDIR, GDAL_DATA, GDAL_DISABLE_CPLLOCALEC, GDAL_FILENAME_IS_UTF8, 
	GEOTIFF_CSV, GDAL_DISABLE_READDIR_ON_OPEN, GDAL_CACHEMAX, GDAL_SKIP, GDAL_DRIVER_PATH, 
	GDAL_FORCE_CACHING, GDAL_VALIDATE_CREATION_OPTIONS, GDAL_IGNORE_AXIS_ORIENTATION, GMLJP2OVERRIDE, GDAL_PAM_MODE, 
	GDAL_PAM_PROXY_DIR, GDAL_MAX_DATASET_POOL_SIZE, GDAL_SWATH_SIZE, USE_RRD, GTIFF_IGNORE_READ_ERRORS, 
	ESRI_XML_PAM, JPEG_QUALITY_OVERVIEW, GDAL_TIFF_INTERNAL_MASK, GDAL_TIFF_INTERNAL_MASK_TO_8BIT, TIFF_USE_OVR, 
	GTIFF_POINT_GEO_IGNORE, GTIFF_REPORT_COMPD_CS, GDAL_ENABLE_TIFF_SPLIT, GDAL_TIFF_OVR_BLOCKSIZE, GRIB_NORMALIZE_UNITS, 
	PROJSO, CENTER_LONG, CHECK_WITH_INVERT_PROJ, THRESHOLD, OGR_DEBUG_ORGANIZE_POLYGONS, 
	OGR_ARC_STEPSIZE, OGR_ENABLE_PARTIAL_REPROJECTION, OGR_FORCE_ASCII, SHAPE_ENCODING, DXF_ENCODING, 
	GML_INVERT_AXIS_ORDER_IF_LAT_LONG, GML_CONSIDER_EPSG_AS_URN, GML_SAVE_RESOLVED_TO, GML_SKIP_RESOLVE_ELEMS, GML_FIELDTYPES, 
	OGR_WFS_PAGING_ALLOWED, OGR_WFS_PAGE_SIZE, OGR_WFS_LOAD_MULTIPLE_LAYER_DEFN, OGR_EDIGEO_FONT_SIZE_FACTOR, OGR_EDIGEO_CREATE_LABEL_LAYERS, 
	OGR_EDIGEO_RECODE_TO_UTF8, COMPRESS_OVERVIEW, INTERLEAVE_OVERVIEW, PHOTOMETRIC_OVERVIEW;

}